--- #YAML:1.0
name:               Digest-Skein
version:            0.04
abstract:           Perl interface to the Skein digest algorithm
author:
    - Radoslaw Zielinski <radek@pld-linux.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest:        0
    MIME::Base64:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
